/**
 * MBS Hunt Platform — Bend Old Mill District Scavenger Hunt
 *
 * 24 Mike Bennett animal character stops.
 * Stops 1-15 are confirmed installations. Stops 16-24 are TBD placeholders (is_active=false).
 * Stop 12 (Mountain Lion) is a bonus stop.
 */
import { useHuntStore } from '../stores/huntStore.js';

const BEND_HUNT = {
  id: 'HNT-bend-oldmill',
  name: 'PNW Animal Scavenger Hunt',
  city: 'Bend, OR',
  slug: 'bend-old-mill',
  emoji: '🏔️',
  description:
    'Discover hidden PNW animal characters across the Old Mill District! A collaboration between Mike Bennett Studios and The Zoo Quarium. Solve riddles, scan QR codes, and collect every character card!',
  status: 'published',
  rewardUrl: null,
  createdAt: '2026-04-01T00:00:00.000Z',
  stops: [
    // ── Confirmed installations (1-15) ──
    {
      id: 'STP-BEND-01', slug: 'standing-black-bear', sortOrder: 1,
      character_name: 'Standing Black Bear',
      character_species: 'Black Bear',
      sponsor_business: 'Banana Republic',
      install_type: 'Asphalt Art',
      placement_notes: 'Banana Republic storefront area',
      is_active: true,
      animal_fun_fact_1: 'Black bears can run up to 35 mph — faster than most humans!',
      animal_fun_fact_2: 'Despite their name, they can be brown, cinnamon, or even blonde.',
      riddle_clue: 'I stand tall where fashion meets the wild, a furry friend with a gentle smile...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 55, mapY: 32,
      prompt: 'Stand tall like a bear!',
    },
    {
      id: 'STP-BEND-02', slug: 'northern-flying-squirrel', sortOrder: 2,
      character_name: 'Northern Flying Squirrel',
      character_species: 'Northern Flying Squirrel',
      sponsor_business: 'Banana Republic',
      install_type: 'Asphalt Art',
      placement_notes: 'Banana Republic — second installation',
      is_active: true,
      animal_fun_fact_1: 'Flying squirrels don\'t actually fly — they glide up to 150 feet using skin flaps!',
      animal_fun_fact_2: 'They\'re nocturnal and have huge eyes to see in the dark.',
      riddle_clue: 'I leap and glide through the night air, look down — you\'ll find me if you dare...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 53, mapY: 34,
      prompt: 'Spread your arms like you\'re gliding!',
    },
    {
      id: 'STP-BEND-03', slug: 'porcupine', sortOrder: 3,
      character_name: 'Porcupine',
      character_species: 'North American Porcupine',
      sponsor_business: 'Stacks Restaurant',
      install_type: 'Asphalt Art',
      placement_notes: 'Stacks Restaurant exterior',
      is_active: true,
      animal_fun_fact_1: 'Porcupines have about 30,000 quills that grow back when lost!',
      animal_fun_fact_2: 'They\'re excellent tree climbers and love to eat bark.',
      riddle_clue: 'Don\'t get too close — I\'m a prickly fellow, near stacks of something warm and mellow...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 48, mapY: 40,
      prompt: 'Show us your prickliest face!',
    },
    {
      id: 'STP-BEND-04', slug: 'chinook-salmon', sortOrder: 4,
      character_name: 'Chinook Salmon',
      character_species: 'Chinook Salmon',
      sponsor_business: 'Anthony\'s Restaurant',
      install_type: 'Double Post Mount',
      placement_notes: 'Anthony\'s Restaurant entrance area',
      is_active: true,
      animal_fun_fact_1: 'Chinook salmon are the largest Pacific salmon — up to 130 pounds!',
      animal_fun_fact_2: 'They can leap 12 feet to clear waterfalls on their journey home.',
      riddle_clue: 'I swim upstream against the flow, near a place where diners go...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 38, mapY: 72,
      prompt: 'Pretend you\'re a salmon jumping upstream!',
    },
    {
      id: 'STP-BEND-05', slug: 'gray-wolf', sortOrder: 5,
      character_name: 'Gray Wolf',
      character_species: 'Gray Wolf',
      sponsor_business: 'Greg\'s Grill',
      install_type: 'Double Post Mount',
      placement_notes: 'Greg\'s Grill exterior',
      is_active: true,
      animal_fun_fact_1: 'Wolves can hear sounds up to 10 miles away in open terrain!',
      animal_fun_fact_2: 'A wolf pack can travel up to 30 miles in a single day.',
      riddle_clue: 'I howl at the moon and run with my pack, near the grill where flavors don\'t lack...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 42, mapY: 68,
      prompt: 'Give us your best wolf howl!',
    },
    {
      id: 'STP-BEND-06', slug: 'bald-eagle', sortOrder: 6,
      character_name: 'Bald Eagle',
      character_species: 'Bald Eagle',
      sponsor_business: 'Savory Spice Shop',
      install_type: 'Asphalt Art',
      placement_notes: 'Savory Spice Shop storefront',
      is_active: true,
      animal_fun_fact_1: 'Bald eagles can see fish from over a mile away!',
      animal_fun_fact_2: 'Their nests can weigh over 2 tons and are used for decades.',
      riddle_clue: 'I soar above with eyes so keen, near savory scents I can be seen...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 50, mapY: 44,
      prompt: 'Spread your wings like an eagle!',
    },
    {
      id: 'STP-BEND-07', slug: 'rattlesnake', sortOrder: 7,
      character_name: 'Rattlesnake',
      character_species: 'Western Rattlesnake',
      sponsor_business: 'Anthropologie',
      install_type: 'Window Cling',
      placement_notes: 'Anthropologie window display',
      is_active: true,
      animal_fun_fact_1: 'Rattlesnakes add a new rattle segment every time they shed their skin!',
      animal_fun_fact_2: 'They can sense body heat with special pits on their face.',
      riddle_clue: 'I rattle and hiss but don\'t be afraid, look through the glass where I\'m displayed...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 52, mapY: 48,
      prompt: 'Do your best snake dance!',
    },
    {
      id: 'STP-BEND-08', slug: 'three-ducks', sortOrder: 8,
      character_name: 'Three Ducks',
      character_species: 'Mallard Duck',
      sponsor_business: 'South Pond',
      install_type: 'Wall and Post Mount',
      placement_notes: 'South Pond area — wall and post installation',
      is_active: true,
      animal_fun_fact_1: 'Ducks have waterproof feathers — they stay dry even when diving!',
      animal_fun_fact_2: 'Ducklings can swim and find food on their own within hours of hatching.',
      riddle_clue: 'We waddle in threes near water so still, quacking our way with a jolly goodwill...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 35, mapY: 78,
      prompt: 'Waddle like a duck with two friends!',
    },
    {
      id: 'STP-BEND-09', slug: 'blue-heron', sortOrder: 9,
      character_name: 'Blue Heron',
      character_species: 'Great Blue Heron',
      sponsor_business: 'South Pond Waterfall',
      install_type: 'Double Post Mount',
      placement_notes: 'Near the South Pond waterfall',
      is_active: true,
      animal_fun_fact_1: 'Great blue herons can strike prey in 1/60th of a second!',
      animal_fun_fact_2: 'They stand completely still for hours waiting for fish — the ultimate patience.',
      riddle_clue: 'Still as a statue by falling water, I wait and watch like nature taught her...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 32, mapY: 82,
      prompt: 'Stand perfectly still like a heron!',
    },
    {
      id: 'STP-BEND-10', slug: 'river-otter', sortOrder: 10,
      character_name: 'River Otter',
      character_species: 'North American River Otter',
      sponsor_business: 'North Pond',
      install_type: 'Double Post Mount',
      placement_notes: 'North Pond area',
      is_active: true,
      animal_fun_fact_1: 'River otters can hold their breath for up to 8 minutes underwater!',
      animal_fun_fact_2: 'They slide on their bellies through mud and snow just for fun.',
      riddle_clue: 'I slide and splash where the water\'s calm, near the north pond I\'m a slippery charm...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 45, mapY: 55,
      prompt: 'Do your best otter belly slide pose!',
    },
    {
      id: 'STP-BEND-11', slug: 'rock-chuck', sortOrder: 11,
      character_name: 'Yellow-bellied Marmot',
      character_species: 'Yellow-bellied Marmot (Rock Chuck)',
      sponsor_business: 'REI',
      install_type: 'Asphalt Art',
      placement_notes: 'REI storefront area',
      is_active: true,
      animal_fun_fact_1: 'Marmots hibernate for up to 8 months — the longest nap in North America!',
      animal_fun_fact_2: 'They whistle loudly to warn their colony of danger — earning the name "whistle pig."',
      riddle_clue: 'I sun on rocks near adventure gear, my whistle says danger is near...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 18, mapY: 40,
      prompt: 'Show us your adventure face!',
    },
    {
      id: 'STP-BEND-12', slug: 'mountain-lion', sortOrder: 12,
      character_name: 'Mountain Lion',
      character_species: 'Mountain Lion (Cougar)',
      sponsor_business: 'NE Parking',
      install_type: 'Asphalt Art',
      placement_notes: 'Northeast parking area',
      is_active: true,
      isBonus: true,
      animal_fun_fact_1: 'Mountain lions can leap 40 feet horizontally in a single bound!',
      animal_fun_fact_2: 'They\'re the largest cat that can still purr — but they can\'t roar.',
      riddle_clue: 'Silent and powerful, I prowl the edge, a bonus find near the parking ledge...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 75, mapY: 20,
      prompt: 'Show us your fiercest cat pose!',
    },
    {
      id: 'STP-BEND-13', slug: 'mule-deer', sortOrder: 13,
      character_name: 'Mule Deer',
      character_species: 'Mule Deer',
      sponsor_business: 'Grass Patch',
      install_type: 'Double Post Mount',
      placement_notes: 'Grass patch area',
      is_active: true,
      animal_fun_fact_1: 'Mule deer get their name from their large, mule-like ears!',
      animal_fun_fact_2: 'They bounce with all four feet hitting the ground at once — called "stotting."',
      riddle_clue: 'Big ears and gentle eyes in the green, on a grassy patch I can be seen...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 62, mapY: 50,
      prompt: 'Do the mule deer bounce — all four feet!',
    },
    {
      id: 'STP-BEND-14', slug: 'great-horned-owl', sortOrder: 14,
      character_name: 'Great Horned Owl',
      character_species: 'Great Horned Owl',
      sponsor_business: 'American Eagle',
      install_type: 'Asphalt Art',
      placement_notes: 'American Eagle storefront',
      is_active: true,
      animal_fun_fact_1: 'Great horned owls can rotate their heads 270 degrees!',
      animal_fun_fact_2: 'They\'re one of the few animals that regularly eat skunks.',
      riddle_clue: 'Who watches from where the eagle lands? My horns aren\'t what you think — they\'re feathered bands...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 58, mapY: 38,
      prompt: 'Give us your best owl head turn!',
    },
    {
      id: 'STP-BEND-15', slug: 'elk', sortOrder: 15,
      character_name: 'Elk',
      character_species: 'Roosevelt Elk',
      sponsor_business: 'Stacks Diner',
      install_type: 'Wall Mount',
      placement_notes: 'Stacks Diner wall installation',
      is_active: true,
      animal_fun_fact_1: 'Bull elk antlers can grow up to 4 feet long and weigh 40 pounds!',
      animal_fun_fact_2: 'Elk bugle — a haunting, high-pitched call that echoes through mountain valleys.',
      riddle_clue: 'Majestic and proud, I hang on the wall, near stacks of pancakes standing tall...',
      character_backstory: '',
      mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 46, mapY: 42,
      prompt: 'Strike your most majestic pose!',
    },
    // ── TBD Placeholders (16-24) — is_active=false ──
    {
      id: 'STP-BEND-16', slug: 'tbd-16', sortOrder: 16,
      character_name: 'TBD', character_species: 'TBD',
      sponsor_business: 'TBD', install_type: 'TBD', placement_notes: '',
      is_active: false,
      animal_fun_fact_1: '', animal_fun_fact_2: '', riddle_clue: '',
      character_backstory: '', mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 0, mapY: 0, prompt: '',
    },
    {
      id: 'STP-BEND-17', slug: 'tbd-17', sortOrder: 17,
      character_name: 'TBD', character_species: 'TBD',
      sponsor_business: 'TBD', install_type: 'TBD', placement_notes: '',
      is_active: false,
      animal_fun_fact_1: '', animal_fun_fact_2: '', riddle_clue: '',
      character_backstory: '', mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 0, mapY: 0, prompt: '',
    },
    {
      id: 'STP-BEND-18', slug: 'tbd-18', sortOrder: 18,
      character_name: 'TBD', character_species: 'TBD',
      sponsor_business: 'TBD', install_type: 'TBD', placement_notes: '',
      is_active: false,
      animal_fun_fact_1: '', animal_fun_fact_2: '', riddle_clue: '',
      character_backstory: '', mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 0, mapY: 0, prompt: '',
    },
    {
      id: 'STP-BEND-19', slug: 'tbd-19', sortOrder: 19,
      character_name: 'TBD', character_species: 'TBD',
      sponsor_business: 'TBD', install_type: 'TBD', placement_notes: '',
      is_active: false,
      animal_fun_fact_1: '', animal_fun_fact_2: '', riddle_clue: '',
      character_backstory: '', mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 0, mapY: 0, prompt: '',
    },
    {
      id: 'STP-BEND-20', slug: 'tbd-20', sortOrder: 20,
      character_name: 'TBD', character_species: 'TBD',
      sponsor_business: 'TBD', install_type: 'TBD', placement_notes: '',
      is_active: false,
      animal_fun_fact_1: '', animal_fun_fact_2: '', riddle_clue: '',
      character_backstory: '', mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 0, mapY: 0, prompt: '',
    },
    {
      id: 'STP-BEND-21', slug: 'tbd-21', sortOrder: 21,
      character_name: 'TBD', character_species: 'TBD',
      sponsor_business: 'TBD', install_type: 'TBD', placement_notes: '',
      is_active: false,
      animal_fun_fact_1: '', animal_fun_fact_2: '', riddle_clue: '',
      character_backstory: '', mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 0, mapY: 0, prompt: '',
    },
    {
      id: 'STP-BEND-22', slug: 'tbd-22', sortOrder: 22,
      character_name: 'TBD', character_species: 'TBD',
      sponsor_business: 'TBD', install_type: 'TBD', placement_notes: '',
      is_active: false,
      animal_fun_fact_1: '', animal_fun_fact_2: '', riddle_clue: '',
      character_backstory: '', mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 0, mapY: 0, prompt: '',
    },
    {
      id: 'STP-BEND-23', slug: 'tbd-23', sortOrder: 23,
      character_name: 'TBD', character_species: 'TBD',
      sponsor_business: 'TBD', install_type: 'TBD', placement_notes: '',
      is_active: false,
      animal_fun_fact_1: '', animal_fun_fact_2: '', riddle_clue: '',
      character_backstory: '', mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 0, mapY: 0, prompt: '',
    },
    {
      id: 'STP-BEND-24', slug: 'tbd-24', sortOrder: 24,
      character_name: 'TBD', character_species: 'TBD',
      sponsor_business: 'TBD', install_type: 'TBD', placement_notes: '',
      is_active: false,
      animal_fun_fact_1: '', animal_fun_fact_2: '', riddle_clue: '',
      character_backstory: '', mike_note: '',
      silhouette_url: null, card_art_url: null, photoUrl: null,
      mapX: 0, mapY: 0, prompt: '',
    },
  ],
};

export function loadBendSeedData(force = false) {
  const store = useHuntStore.getState();
  if (force) store.removeHunt(BEND_HUNT.id);
  if (store.hunts.some((h) => h.id === BEND_HUNT.id)) return false;
  store.addHunt(BEND_HUNT);
  return true;
}

export function clearBendSeedData() {
  useHuntStore.getState().removeHunt(BEND_HUNT.id);
}

export const BEND_HUNT_ID = BEND_HUNT.id;
